# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3716d2bb03c8751d3df5b956296a5f6e78f1467aaa5616661fc1bf3b96a8ccc086fcbf95a11bcdb95d0c3ebfe444c71ab683e7049ab9d4a288b06f49cc60a0b3

test:
  secret_key_base: 17866f4d14a681769229bfbde4d46dea78655656e94ffd76535dab6dc7ec15ae550f637344c07b525556e9606b20e67c1642e84a60ce669e5a9fd58e490e9c3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
